app = "matans-test-app-flyio"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  HOST = "https://matans-test-app-flyio.fly.dev"
  PORT = "8081"
  SCOPES = "write_products,read_discounts"
  SHOPIFY_API_KEY = "2dc898dce5d82bb6db3908c13766fc8e"

[build.args]
  SHOPIFY_API_KEY="2dc898dce5d82bb6db3908c13766fc8e"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "data"

[[services]]
  http_checks = []
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
