name: Fly Deploy Dev App
on:
  push:
    branches:
      - dev
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  SHOPIFY_API_KEY_DEV: ${{ secrets.SHOPIFY_API_KEY_DEV }}
  APP_NAME: "matans-test-app-dev"
  HOST: "https://matans-test-app-dev.fly.dev"
jobs:
  deploy:
      name: Deploy Dev App
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only --build-arg SHOPIFY_API_KEY=${{secrets.SHOPIFY_API_KEY_DEV}} -a ${{APP_NAME}}
