name: Fly Deploy Production App
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
jobs:
  deploy:
      name: Deploy dev app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only --build-arg SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY}}
